### ISSUE TITLE
Can't run the code in Windows10+Ubuntu

### ISSUE THREAD

**Issue by kiwimaker** [atawfique21/SeleniumRedis#1]
Hi Abir, I was just testing the code and I hitted a pothole.

I am using w10 to run flask/selenium + Ubuntu (from Windows Store) to run redis.

After install everything and run all the three consoles, I installed Postman to do the requests, and I got this:

flask
```
127.0.0.1 - - [30/Jun/2021 19:45:42] "←[37mGET /run HTTP/1.1←[0m" 200 -
```
red.py
```
19:45:42 ←[31mWorker rq:worker:afe5eec3cc5a4f5fbf2e7b0322f48512: found an unhandled exception, quitting...←[39;49;00m
Traceback (most recent call last):
  File "C:\Users\kiwi\Desktop\python\SeleniumRedis\lib\site-packages\rq\worker.py", line 549, in work
    self.execute_job(job, queue)
  File "C:\Users\kiwi\Desktop\python\SeleniumRedis\lib\site-packages\rq\worker.py", line 773, in execute_job
    self.fork_work_horse(job, queue)
  File "C:\Users\kiwi\Desktop\python\SeleniumRedis\lib\site-packages\rq\worker.py", line 698, in fork_work_horse
    child_pid = os.fork()
AttributeError: module 'os' has no attribute 'fork'
```

Of course I went straight to Google to see if I could fix this error, but it seems that is almost a [dead-end in Windows](https://stackoverflow.com/questions/17300551/how-to-run-python-script-with-os-fork-on-windows).

Do you have any thoughts about how to fix this or we should use full ubuntu to try this setup?

Thanks a lot for the code and for the medium article. Very interesting. Good work!!

**Comment by atawfique21** [comment]
Hi there, 

For some context: I run all of the SeleniumRedis code either on MacOS or a DigitalOcean hosted Ubuntu server. This is why I have not encountered this specific error before. 

This error, as you can probably tell, has to do with Redis. On Windows, `os.fork()` does not exist and there is no direct work-around unless you were to code `.fork()` yourself with multithreading, but that opens a can of worms as you will also need to code other modules as well. So that is not a real option. 

After doing some research, I've discovered that using [Cygwin ](https://www.cygwin.com/) to run the Python code is perhaps the easiest way to approach this. From my understanding (and I can be totally wrong), Cygwin runs the code as if it were to be run on any Linux based system. If this does indeed work and you continue to use Windows to develop Python, I strongly suggest using Cygwin to run all of your Python code to avoid errors in future projects. [Here ](https://stackoverflow.com/a/1921019) is a brief stackoverflow answer on how to do this. 

And again: I do not develop on Windows so I'd very much appreciate a follow-up to this after testing and let me know if this is indeed a fix to this issue so I can update the readme section of the repo!

Also: thanks for the appreciation! I very much still use this code for every single Selenium project I do and will continue to support it.

**Comment by kiwimaker** [comment]
Hi again Abir, 

so I finally got it running, but I had to use [this repo](https://github.com/michaelbrooks/rq-win) to make it work. It seems is a work-around to use a redis worker in windows.

Right now I'm using:
- redis vía Ubuntu 18.04 in WSL (W10)
- flask vía Ubuntu 18.04 in WSL (W10) / directly in W10 (works both ways)
- redis worker vía rq-win in W10
- Postman in W10

This way I can keep programming in w10 and I dont need to make a new partition to use Ubuntu/Linux.

Another viable setup (if you want to use the original redis workers):
- redis via Ubuntu WSL
- flask vía Ubuntu WSL / W10
- redis worker via Ubuntu WSL
- vcxsrv vía Windows 10 (to use GUI with Ubuntu WSL): [info](https://www.gregbrisebois.com/posts/chromedriver-in-wsl2/)



Right now I'm doing some other stuff with Selenium and I cant prioritize further testing, but: Yes, the requests works and I got Selenium up and running. All the requests are fine. 

Again, thanks a lot for this repo, I will follow the development closely and hope to be able to use it more in the coming weeks.
